#!/bin/bash

p=$(readlink $0) || p=$0
d=$(dirname  $p)
b=$(basename $p)

jruby=$d/jruby-complete.jar

if [[ ! -f "$jruby" ]]
then
  echo "Cannot find '$jruby'."
  exit 1
fi

export DDTSHOME=$d
export DDTSAPP=`pwd`/app
export DDTSOUT=`pwd`

ulimit -St unlimited && java -Xms512m -Xmx2048m -jar $jruby --1.9 -I. $d/ts.rb $b $*
